#+TITLE: 编程珠玑
#+AUTHOR: qiaoin
#+EMAIL: qiao.liubing@gmail.com
#+OPTIONS: toc:3 num:nil
#+STARTUP: showall

在本书的 *前言* 部分，作者写到：
#+BEGIN_QUOTE
计算机编程有很多方面。Fred Brooks在《人月神话》一书中为我们描绘了全景，他的文章强调了管理在大型软件项目中
所起的关键作用。而Steve McConnell在《代码大全》一书中更具体地传授了良好的编程风格。这两本书所讨论的是好
软件的关键因素和专业程序员应有的特征。遗憾的是，仅仅熟练地运用这些可靠的工程原理，不见得一定能够如期完成软件
并顺利运行。
#+END_QUOTE

#+BEGIN_QUOTE
本书描述了计算机编程更具魅力的一面：在可靠的工程之外，在洞察力和创造力范围内结晶而出的 *编程珠玑* 。
#+END_QUOTE

#+BEGIN_QUOTE
本书每一章都独立成篇，各章之间却又有着逻辑分组。第1章至第5章构成本书的第一部分，这部分回顾了编程的基本原理：
问题定义，算法，数据结构以及程序验证和测试。第二部分围绕效率这个主题展开。效率问题有时本身就很重要，又永远
都是进入有趣编程问题的绝佳跳板。第三部分用这些技术来解决排序，搜索和字符串等重要问题。
#+END_QUOTE

#+BEGIN_QUOTE
阅读本书的一个提示：不要读得太快。要仔细阅读，一次读一章。要尝试解答书中提出的问题——有些问题需要集中精力思考
一两个小时才会想清楚。然后，要努力解答每章末尾的习题：当读者写下答案时，从本书学到的大部分知识就会跃然纸上。
如有可能，要先与朋友和同事讨论一下自己的思路，再去查阅本书末尾的提示和答案。每章末尾的“深入阅读”并不算是学术
意义上的参考文献表，而只是我个人推荐的一些好书，我自己就收藏了这些书。
#+END_QUOTE

Part I: PRELIMINARIES 准备工作
- [[./column1-cracking-the-oyster.org][开篇]] 

  This column is the history of a single problem. A combination of careful problem definition and straightforward programming techniques led to an elegant solution. The column illustrates the central theme of this book: thinking hard about a real case study can be fun and can also lead to practical benefits.

- 啊哈！算法 

  This column examines three problems, with an emphasis on how algorithmic insights can yield simple and effective code.

- 数据决定程序结构

  This column surveys the crucial role that the structure of data can play in software design.

- 编写正确的程序
  
  This column introduces *program verification* as a tool for writing correct code. Verification techniques are used extensively as we derive subtle (and fast) functions in Columns 9, 11 and 14.

- 编程中的次要问题
  
  This column shows how we implement those abstract programs in real code: we use scaffolding to probe a function, to bombard it with test cases, and to measure its performance.

Part II: PERFORMANCE
- 程序性能分析
- 粗略估算
- 算法设计技术
- 代码调优
- 节省空间

Part III: THE PRODUCT
- 排序
- 取样问题
- 搜索
- 堆
- 字符串
